const API_ROUTES = {
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  LOGOUT: "/logout",
  AUTH: "/auth",
  ALL_HOTEL_DATA: "/all-hotel",
  FETCH_USER_BOOKING: "/bookings",
  SEARCH: "/search-hotel",
  GET_ALL_USERS: "/admin/get-all-users",
  GET_ADMIN_DASHBOARD_DATA: "/admin/get-dashboard-details",
  GET_ADMIN_BOOKING_DATA: "/admin/all-bookings",
  UPDATE_USER_PROFILE: "/update-profile",
  CHANGE_PASSWORD: "/change-password",
  ROOM_DETAILS: "/room-details",
  BOOK_HOTEL: "/book-hotel",
  UPDATE_HOTEL_DETAILS: "/admin/update-hotel-details",
  DELETE_ROOM: "/admin/delete-room",
  UPDATE_ROOM_DETAILS: "/admin/update-room-details",
  ADD_ROOM: "/admin/add-room",
  ADD_NEW_HOTEL: "/admin/add-hotel",
  REMOVE_HOTEL: "/admin/remove-hotel",
  UPDATE_ROLE_USER: "/admin/create-admin",
  UPDATE_STATUS_USER: "/admin/block-user",
  UPDATE_BOOKING_STATUS: "/update-booking-status",
  UPDATE_BOOKING_DETAILS: "/update-booking-details",
  ADD_HOTEL_REVIEW: "/add-hotel-review",
};

export default API_ROUTES;
